# Generated by Django 4.2.3 on 2023-07-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteachers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studentteachers',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.teacher'),
        ),
    ]
